/* tslint:disable */
/* eslint-disable */
/**
 * System REST API
 *  This page provides documentation for the System REST API.  If you have any questions or need support, please contact us at the email provided.  ## Formatting query parameters  Filters should be formatted as `field:value` and use the logical OR operator `||` to specify an OR condition. (We\'ve deprecated the pipe operator for OR conditions.)   If they are numerical, they should be formatted as `field:opvalue`. Examples: - `doi:10.1234/5678||10.8765/4321` - `num_findings:>2`  Sorts should be formatted as `field:direction`. Examples: - `cited_by:desc` - `publish_date:asc`  Searches should be formatted as `field:value`. Examples: - `name:osteoporosis` 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: api@system.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
  ListResponseMechanisticFinding,
  MechanisticFinding,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    ListResponseMechanisticFindingFromJSON,
    ListResponseMechanisticFindingToJSON,
    MechanisticFindingFromJSON,
    MechanisticFindingToJSON,
} from '../models/index';

export interface GetMechanisticFindingByIdRequest {
    findingId: string;
}

export interface GetMechanisticFindingsRequest {
    filter?: string | null;
    sort?: string | null;
    search?: string | null;
    fields?: string | null;
    includeTotal?: boolean | null;
    offset?: number;
    limit?: number;
}

/**
 * 
 */
export class MechanisticFindingsApi extends runtime.BaseAPI {

    /**
     * Get a mechanistic finding by its ID.
     * Get a mechanistic finding
     */
    async getMechanisticFindingByIdRaw(requestParameters: GetMechanisticFindingByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MechanisticFinding>> {
        if (requestParameters['findingId'] == null) {
            throw new runtime.RequiredError(
                'findingId',
                'Required parameter "findingId" was null or undefined when calling getMechanisticFindingById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // APIKeyHeader authentication
        }

        const response = await this.request({
            path: `/v0/mechanistic_findings/{finding_id}`.replace(`{${"finding_id"}}`, encodeURIComponent(String(requestParameters['findingId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MechanisticFindingFromJSON(jsonValue));
    }

    /**
     * Get a mechanistic finding by its ID.
     * Get a mechanistic finding
     */
    async getMechanisticFindingById(requestParameters: GetMechanisticFindingByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MechanisticFinding> {
        const response = await this.getMechanisticFindingByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get a list of mechanistic findings.
     * Get mechanistic findings
     */
    async getMechanisticFindingsRaw(requestParameters: GetMechanisticFindingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListResponseMechanisticFinding>> {
        const queryParameters: any = {};

        if (requestParameters['filter'] != null) {
            queryParameters['filter'] = requestParameters['filter'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        if (requestParameters['search'] != null) {
            queryParameters['search'] = requestParameters['search'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['fields'] = requestParameters['fields'];
        }

        if (requestParameters['includeTotal'] != null) {
            queryParameters['include_total'] = requestParameters['includeTotal'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // APIKeyHeader authentication
        }

        const response = await this.request({
            path: `/v0/mechanistic_findings`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListResponseMechanisticFindingFromJSON(jsonValue));
    }

    /**
     * Get a list of mechanistic findings.
     * Get mechanistic findings
     */
    async getMechanisticFindings(requestParameters: GetMechanisticFindingsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListResponseMechanisticFinding> {
        const response = await this.getMechanisticFindingsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
