/* tslint:disable */
/* eslint-disable */
/**
 * System REST API
 *  This page provides documentation for the System REST API.  If you have any questions or need support, please contact us at the email provided.  ## Formatting query parameters  Filters should be formatted as `field:value` and use the logical OR operator `||` to specify an OR condition. (We\'ve deprecated the pipe operator for OR conditions.)   If they are numerical, they should be formatted as `field:opvalue`. Examples: - `doi:10.1234/5678||10.8765/4321` - `num_findings:>2`  Sorts should be formatted as `field:direction`. Examples: - `cited_by:desc` - `publish_date:asc`  Searches should be formatted as `field:value`. Examples: - `name:osteoporosis` 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: api@system.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
  ListResponseRelationship,
  ListResponseStatisticalFinding,
  ListResponseStudy,
  Relationship,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    ListResponseRelationshipFromJSON,
    ListResponseRelationshipToJSON,
    ListResponseStatisticalFindingFromJSON,
    ListResponseStatisticalFindingToJSON,
    ListResponseStudyFromJSON,
    ListResponseStudyToJSON,
    RelationshipFromJSON,
    RelationshipToJSON,
} from '../models/index';

export interface GetRelationshipByIdRequest {
    relationshipId: string;
}

export interface GetRelationshipStatisticalFindingsRequest {
    relationshipId: string;
    filter?: string | null;
    sort?: string | null;
    search?: string | null;
    fields?: string | null;
    includeTotal?: boolean | null;
    offset?: number;
    limit?: number;
}

export interface GetRelationshipStudiesRequest {
    relationshipId: string;
    filter?: string | null;
    sort?: string | null;
    search?: string | null;
    fields?: string | null;
    includeTotal?: boolean | null;
    offset?: number;
    limit?: number;
}

export interface GetRelationshipsRequest {
    filter?: string | null;
    sort?: string | null;
    search?: string | null;
    fields?: string | null;
    includeTotal?: boolean | null;
    offset?: number;
    limit?: number;
}

/**
 * 
 */
export class RelationshipsApi extends runtime.BaseAPI {

    /**
     * Get a relationship by its ID.
     * Get a relationship
     */
    async getRelationshipByIdRaw(requestParameters: GetRelationshipByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Relationship>> {
        if (requestParameters['relationshipId'] == null) {
            throw new runtime.RequiredError(
                'relationshipId',
                'Required parameter "relationshipId" was null or undefined when calling getRelationshipById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // APIKeyHeader authentication
        }

        const response = await this.request({
            path: `/v0/relationships/{relationship_id}`.replace(`{${"relationship_id"}}`, encodeURIComponent(String(requestParameters['relationshipId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RelationshipFromJSON(jsonValue));
    }

    /**
     * Get a relationship by its ID.
     * Get a relationship
     */
    async getRelationshipById(requestParameters: GetRelationshipByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Relationship> {
        const response = await this.getRelationshipByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get a list of the statistical findings underlying a given relationship.
     * Get relationship statistical findings
     */
    async getRelationshipStatisticalFindingsRaw(requestParameters: GetRelationshipStatisticalFindingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListResponseStatisticalFinding>> {
        if (requestParameters['relationshipId'] == null) {
            throw new runtime.RequiredError(
                'relationshipId',
                'Required parameter "relationshipId" was null or undefined when calling getRelationshipStatisticalFindings().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['filter'] != null) {
            queryParameters['filter'] = requestParameters['filter'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        if (requestParameters['search'] != null) {
            queryParameters['search'] = requestParameters['search'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['fields'] = requestParameters['fields'];
        }

        if (requestParameters['includeTotal'] != null) {
            queryParameters['include_total'] = requestParameters['includeTotal'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // APIKeyHeader authentication
        }

        const response = await this.request({
            path: `/v0/relationships/{relationship_id}/statistical_findings`.replace(`{${"relationship_id"}}`, encodeURIComponent(String(requestParameters['relationshipId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListResponseStatisticalFindingFromJSON(jsonValue));
    }

    /**
     * Get a list of the statistical findings underlying a given relationship.
     * Get relationship statistical findings
     */
    async getRelationshipStatisticalFindings(requestParameters: GetRelationshipStatisticalFindingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListResponseStatisticalFinding> {
        const response = await this.getRelationshipStatisticalFindingsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get a list of the studies underlying a given relationship.
     * Get relationship studies
     */
    async getRelationshipStudiesRaw(requestParameters: GetRelationshipStudiesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListResponseStudy>> {
        if (requestParameters['relationshipId'] == null) {
            throw new runtime.RequiredError(
                'relationshipId',
                'Required parameter "relationshipId" was null or undefined when calling getRelationshipStudies().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['filter'] != null) {
            queryParameters['filter'] = requestParameters['filter'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        if (requestParameters['search'] != null) {
            queryParameters['search'] = requestParameters['search'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['fields'] = requestParameters['fields'];
        }

        if (requestParameters['includeTotal'] != null) {
            queryParameters['include_total'] = requestParameters['includeTotal'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // APIKeyHeader authentication
        }

        const response = await this.request({
            path: `/v0/relationships/{relationship_id}/studies`.replace(`{${"relationship_id"}}`, encodeURIComponent(String(requestParameters['relationshipId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListResponseStudyFromJSON(jsonValue));
    }

    /**
     * Get a list of the studies underlying a given relationship.
     * Get relationship studies
     */
    async getRelationshipStudies(requestParameters: GetRelationshipStudiesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListResponseStudy> {
        const response = await this.getRelationshipStudiesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get a list of relationships.
     * Get relationships
     */
    async getRelationshipsRaw(requestParameters: GetRelationshipsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListResponseRelationship>> {
        const queryParameters: any = {};

        if (requestParameters['filter'] != null) {
            queryParameters['filter'] = requestParameters['filter'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        if (requestParameters['search'] != null) {
            queryParameters['search'] = requestParameters['search'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['fields'] = requestParameters['fields'];
        }

        if (requestParameters['includeTotal'] != null) {
            queryParameters['include_total'] = requestParameters['includeTotal'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // APIKeyHeader authentication
        }

        const response = await this.request({
            path: `/v0/relationships`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListResponseRelationshipFromJSON(jsonValue));
    }

    /**
     * Get a list of relationships.
     * Get relationships
     */
    async getRelationships(requestParameters: GetRelationshipsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListResponseRelationship> {
        const response = await this.getRelationshipsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
