/* tslint:disable */
/* eslint-disable */
/**
 * System REST API
 *  This page provides documentation for the System REST API.  If you have any questions or need support, please contact us at the email provided.  ## Formatting query parameters  Filters should be formatted as `field:value` and use the logical OR operator `||` to specify an OR condition. (We\'ve deprecated the pipe operator for OR conditions.)   If they are numerical, they should be formatted as `field:opvalue`. Examples: - `doi:10.1234/5678||10.8765/4321` - `num_findings:>2`  Sorts should be formatted as `field:direction`. Examples: - `cited_by:desc` - `publish_date:asc`  Searches should be formatted as `field:value`. Examples: - `name:osteoporosis` 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: api@system.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Flag,
  FlagInput,
  HTTPValidationError,
  ListResponseStatisticalFinding,
  StatisticalFinding,
} from '../models/index';
import {
    FlagFromJSON,
    FlagToJSON,
    FlagInputFromJSON,
    FlagInputToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    ListResponseStatisticalFindingFromJSON,
    ListResponseStatisticalFindingToJSON,
    StatisticalFindingFromJSON,
    StatisticalFindingToJSON,
} from '../models/index';

export interface FlagStatisticalFindingRequest {
    findingId: string;
    flagInput: Array<FlagInput>;
}

export interface GetStatisticalFindingByIdRequest {
    findingId: string;
}

export interface GetStatisticalFindingsRequest {
    filter?: string | null;
    sort?: string | null;
    search?: string | null;
    fields?: string | null;
    includeTotal?: boolean | null;
    offset?: number;
    limit?: number;
}

/**
 * 
 */
export class StatisticalFindingsApi extends runtime.BaseAPI {

    /**
     * Flag a statistical finding for review.
     * Flag statistical finding
     */
    async flagStatisticalFindingRaw(requestParameters: FlagStatisticalFindingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Flag>>> {
        if (requestParameters['findingId'] == null) {
            throw new runtime.RequiredError(
                'findingId',
                'Required parameter "findingId" was null or undefined when calling flagStatisticalFinding().'
            );
        }

        if (requestParameters['flagInput'] == null) {
            throw new runtime.RequiredError(
                'flagInput',
                'Required parameter "flagInput" was null or undefined when calling flagStatisticalFinding().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // APIKeyHeader authentication
        }

        const response = await this.request({
            path: `/v0/statistical_findings/{finding_id}/flags`.replace(`{${"finding_id"}}`, encodeURIComponent(String(requestParameters['findingId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['flagInput']!.map(FlagInputToJSON),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(FlagFromJSON));
    }

    /**
     * Flag a statistical finding for review.
     * Flag statistical finding
     */
    async flagStatisticalFinding(requestParameters: FlagStatisticalFindingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Flag>> {
        const response = await this.flagStatisticalFindingRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get a statistical finding by its ID.
     * Get a statistical finding
     */
    async getStatisticalFindingByIdRaw(requestParameters: GetStatisticalFindingByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StatisticalFinding>> {
        if (requestParameters['findingId'] == null) {
            throw new runtime.RequiredError(
                'findingId',
                'Required parameter "findingId" was null or undefined when calling getStatisticalFindingById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // APIKeyHeader authentication
        }

        const response = await this.request({
            path: `/v0/statistical_findings/{finding_id}`.replace(`{${"finding_id"}}`, encodeURIComponent(String(requestParameters['findingId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StatisticalFindingFromJSON(jsonValue));
    }

    /**
     * Get a statistical finding by its ID.
     * Get a statistical finding
     */
    async getStatisticalFindingById(requestParameters: GetStatisticalFindingByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StatisticalFinding> {
        const response = await this.getStatisticalFindingByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get a list of statistical findings.
     * Get statistical findings
     */
    async getStatisticalFindingsRaw(requestParameters: GetStatisticalFindingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListResponseStatisticalFinding>> {
        const queryParameters: any = {};

        if (requestParameters['filter'] != null) {
            queryParameters['filter'] = requestParameters['filter'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        if (requestParameters['search'] != null) {
            queryParameters['search'] = requestParameters['search'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['fields'] = requestParameters['fields'];
        }

        if (requestParameters['includeTotal'] != null) {
            queryParameters['include_total'] = requestParameters['includeTotal'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // APIKeyHeader authentication
        }

        const response = await this.request({
            path: `/v0/statistical_findings`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListResponseStatisticalFindingFromJSON(jsonValue));
    }

    /**
     * Get a list of statistical findings.
     * Get statistical findings
     */
    async getStatisticalFindings(requestParameters: GetStatisticalFindingsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListResponseStatisticalFinding> {
        const response = await this.getStatisticalFindingsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
