/* tslint:disable */
/* eslint-disable */
/**
 * System REST API
 *  This page provides documentation for the System REST API.  If you have any questions or need support, please contact us at the email provided.  ## Formatting query parameters  Filters should be formatted as `field:value` and use the logical OR operator `||` to specify an OR condition. (We\'ve deprecated the pipe operator for OR conditions.)   If they are numerical, they should be formatted as `field:opvalue`. Examples: - `doi:10.1234/5678||10.8765/4321` - `num_findings:>2`  Sorts should be formatted as `field:direction`. Examples: - `cited_by:desc` - `publish_date:asc`  Searches should be formatted as `field:value`. Examples: - `name:osteoporosis` 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: api@system.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Author.
 * @export
 * @interface Author
 */
export interface Author {
    /**
     * Full name of author
     * @type {string}
     * @memberof Author
     */
    fullName: string;
    /**
     * 
     * @type {string}
     * @memberof Author
     */
    orcid?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Author
     */
    openalexId?: string | null;
}

/**
 * Check if a given object implements the Author interface.
 */
export function instanceOfAuthor(value: object): value is Author {
    if (!('fullName' in value) || value['fullName'] === undefined) return false;
    return true;
}

export function AuthorFromJSON(json: any): Author {
    return AuthorFromJSONTyped(json, false);
}

export function AuthorFromJSONTyped(json: any, ignoreDiscriminator: boolean): Author {
    if (json == null) {
        return json;
    }
    return {
        
        'fullName': json['full_name'],
        'orcid': json['orcid'] == null ? undefined : json['orcid'],
        'openalexId': json['openalex_id'] == null ? undefined : json['openalex_id'],
    };
}

export function AuthorToJSON(value?: Author | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'full_name': value['fullName'],
        'orcid': value['orcid'],
        'openalex_id': value['openalexId'],
    };
}

