/* tslint:disable */
/* eslint-disable */
/**
 * System REST API
 *  This page provides documentation for the System REST API.  If you have any questions or need support, please contact us at the email provided.  ## Formatting query parameters  Filters should be formatted as `field:value` and use the logical OR operator `||` to specify an OR condition. (We\'ve deprecated the pipe operator for OR conditions.)   If they are numerical, they should be formatted as `field:opvalue`. Examples: - `doi:10.1234/5678||10.8765/4321` - `num_findings:>2`  Sorts should be formatted as `field:direction`. Examples: - `cited_by:desc` - `publish_date:asc`  Searches should be formatted as `field:value`. Examples: - `name:osteoporosis` 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: api@system.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CypherProperty } from './CypherProperty';
import {
    CypherPropertyFromJSON,
    CypherPropertyFromJSONTyped,
    CypherPropertyToJSON,
} from './CypherProperty';

/**
 * 
 * @export
 * @interface CypherNodeSchema
 */
export interface CypherNodeSchema {
    /**
     * 
     * @type {string}
     * @memberof CypherNodeSchema
     */
    nodeType: string;
    /**
     * 
     * @type {Array<CypherProperty>}
     * @memberof CypherNodeSchema
     */
    properties: Array<CypherProperty>;
}

/**
 * Check if a given object implements the CypherNodeSchema interface.
 */
export function instanceOfCypherNodeSchema(value: object): value is CypherNodeSchema {
    if (!('nodeType' in value) || value['nodeType'] === undefined) return false;
    if (!('properties' in value) || value['properties'] === undefined) return false;
    return true;
}

export function CypherNodeSchemaFromJSON(json: any): CypherNodeSchema {
    return CypherNodeSchemaFromJSONTyped(json, false);
}

export function CypherNodeSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): CypherNodeSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'nodeType': json['node_type'],
        'properties': ((json['properties'] as Array<any>).map(CypherPropertyFromJSON)),
    };
}

export function CypherNodeSchemaToJSON(value?: CypherNodeSchema | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'node_type': value['nodeType'],
        'properties': ((value['properties'] as Array<any>).map(CypherPropertyToJSON)),
    };
}

