/* tslint:disable */
/* eslint-disable */
/**
 * System REST API
 *  This page provides documentation for the System REST API.  If you have any questions or need support, please contact us at the email provided.  ## Formatting query parameters  Filters should be formatted as `field:value` and use the logical OR operator `||` to specify an OR condition. (We\'ve deprecated the pipe operator for OR conditions.)   If they are numerical, they should be formatted as `field:opvalue`. Examples: - `doi:10.1234/5678||10.8765/4321` - `num_findings:>2`  Sorts should be formatted as `field:direction`. Examples: - `cited_by:desc` - `publish_date:asc`  Searches should be formatted as `field:value`. Examples: - `name:osteoporosis` 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: api@system.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CypherReturnType } from './CypherReturnType';
import {
    CypherReturnTypeFromJSON,
    CypherReturnTypeFromJSONTyped,
    CypherReturnTypeToJSON,
} from './CypherReturnType';

/**
 * 
 * @export
 * @interface CypherStatement
 */
export interface CypherStatement {
    /**
     * 
     * @type {string}
     * @memberof CypherStatement
     */
    statement: string;
    /**
     * 
     * @type {object}
     * @memberof CypherStatement
     */
    parameters?: object | null;
    /**
     * 
     * @type {CypherReturnType}
     * @memberof CypherStatement
     */
    retType?: CypherReturnType | null;
}

/**
 * Check if a given object implements the CypherStatement interface.
 */
export function instanceOfCypherStatement(value: object): value is CypherStatement {
    if (!('statement' in value) || value['statement'] === undefined) return false;
    return true;
}

export function CypherStatementFromJSON(json: any): CypherStatement {
    return CypherStatementFromJSONTyped(json, false);
}

export function CypherStatementFromJSONTyped(json: any, ignoreDiscriminator: boolean): CypherStatement {
    if (json == null) {
        return json;
    }
    return {
        
        'statement': json['statement'],
        'parameters': json['parameters'] == null ? undefined : json['parameters'],
        'retType': json['ret_type'] == null ? undefined : CypherReturnTypeFromJSON(json['ret_type']),
    };
}

export function CypherStatementToJSON(value?: CypherStatement | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'statement': value['statement'],
        'parameters': value['parameters'],
        'ret_type': CypherReturnTypeToJSON(value['retType']),
    };
}

