/* tslint:disable */
/* eslint-disable */
/**
 * System REST API
 *  This page provides documentation for the System REST API.  If you have any questions or need support, please contact us at the email provided.  ## Formatting query parameters  Filters should be formatted as `field:value` and use the logical OR operator `||` to specify an OR condition. (We\'ve deprecated the pipe operator for OR conditions.)   If they are numerical, they should be formatted as `field:opvalue`. Examples: - `doi:10.1234/5678||10.8765/4321` - `num_findings:>2`  Sorts should be formatted as `field:direction`. Examples: - `cited_by:desc` - `publish_date:asc`  Searches should be formatted as `field:value`. Examples: - `name:osteoporosis` 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: api@system.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Type of finding.
 * @export
 */
export const FindingType = {
    Statistical: 'statistical',
    Mechanistic: 'mechanistic'
} as const;
export type FindingType = typeof FindingType[keyof typeof FindingType];


export function instanceOfFindingType(value: any): boolean {
    for (const key in FindingType) {
        if (Object.prototype.hasOwnProperty.call(FindingType, key)) {
            if ((FindingType as Record<string, FindingType>)[key] === value) {
                return true;
            }
        }
    }
    return false;
}

export function FindingTypeFromJSON(json: any): FindingType {
    return FindingTypeFromJSONTyped(json, false);
}

export function FindingTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): FindingType {
    return json as FindingType;
}

export function FindingTypeToJSON(value?: FindingType | null): any {
    return value as any;
}

