/* tslint:disable */
/* eslint-disable */
/**
 * System REST API
 *  This page provides documentation for the System REST API.  If you have any questions or need support, please contact us at the email provided.  ## Formatting query parameters  Filters should be formatted as `field:value` and use the logical OR operator `||` to specify an OR condition. (We\'ve deprecated the pipe operator for OR conditions.)   If they are numerical, they should be formatted as `field:opvalue`. Examples: - `doi:10.1234/5678||10.8765/4321` - `num_findings:>2`  Sorts should be formatted as `field:direction`. Examples: - `cited_by:desc` - `publish_date:asc`  Searches should be formatted as `field:value`. Examples: - `name:osteoporosis` 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: api@system.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * GuidelineGrades
 * @export
 * @interface GuidelineGrades
 */
export interface GuidelineGrades {
    /**
     * 
     * @type {string}
     * @memberof GuidelineGrades
     */
    grade: string;
    /**
     * 
     * @type {string}
     * @memberof GuidelineGrades
     */
    gradeType: string;
    /**
     * 
     * @type {string}
     * @memberof GuidelineGrades
     */
    description: string;
}

/**
 * Check if a given object implements the GuidelineGrades interface.
 */
export function instanceOfGuidelineGrades(value: object): value is GuidelineGrades {
    if (!('grade' in value) || value['grade'] === undefined) return false;
    if (!('gradeType' in value) || value['gradeType'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function GuidelineGradesFromJSON(json: any): GuidelineGrades {
    return GuidelineGradesFromJSONTyped(json, false);
}

export function GuidelineGradesFromJSONTyped(json: any, ignoreDiscriminator: boolean): GuidelineGrades {
    if (json == null) {
        return json;
    }
    return {
        
        'grade': json['grade'],
        'gradeType': json['gradeType'],
        'description': json['description'],
    };
}

export function GuidelineGradesToJSON(value?: GuidelineGrades | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'grade': value['grade'],
        'gradeType': value['gradeType'],
        'description': value['description'],
    };
}

