/* tslint:disable */
/* eslint-disable */
/**
 * System REST API
 *  This page provides documentation for the System REST API.  If you have any questions or need support, please contact us at the email provided.  ## Formatting query parameters  Filters should be formatted as `field:value` and use the logical OR operator `||` to specify an OR condition. (We\'ve deprecated the pipe operator for OR conditions.)   If they are numerical, they should be formatted as `field:opvalue`. Examples: - `doi:10.1234/5678||10.8765/4321` - `num_findings:>2`  Sorts should be formatted as `field:direction`. Examples: - `cited_by:desc` - `publish_date:asc`  Searches should be formatted as `field:value`. Examples: - `name:osteoporosis` 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: api@system.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * GuidelineMetadata
 * @export
 * @interface GuidelineMetadata
 */
export interface GuidelineMetadata {
    /**
     * 
     * @type {string}
     * @memberof GuidelineMetadata
     */
    guideId: string;
    /**
     * 
     * @type {string}
     * @memberof GuidelineMetadata
     */
    title: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof GuidelineMetadata
     */
    authoringSocieties: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof GuidelineMetadata
     */
    link: string;
    /**
     * 
     * @type {string}
     * @memberof GuidelineMetadata
     */
    publishDate: string;
}

/**
 * Check if a given object implements the GuidelineMetadata interface.
 */
export function instanceOfGuidelineMetadata(value: object): value is GuidelineMetadata {
    if (!('guideId' in value) || value['guideId'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('authoringSocieties' in value) || value['authoringSocieties'] === undefined) return false;
    if (!('link' in value) || value['link'] === undefined) return false;
    if (!('publishDate' in value) || value['publishDate'] === undefined) return false;
    return true;
}

export function GuidelineMetadataFromJSON(json: any): GuidelineMetadata {
    return GuidelineMetadataFromJSONTyped(json, false);
}

export function GuidelineMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): GuidelineMetadata {
    if (json == null) {
        return json;
    }
    return {
        
        'guideId': json['guide_id'],
        'title': json['title'],
        'authoringSocieties': json['authoring_societies'],
        'link': json['link'],
        'publishDate': json['publish_date'],
    };
}

export function GuidelineMetadataToJSON(value?: GuidelineMetadata | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'guide_id': value['guideId'],
        'title': value['title'],
        'authoring_societies': value['authoringSocieties'],
        'link': value['link'],
        'publish_date': value['publishDate'],
    };
}

