/* tslint:disable */
/* eslint-disable */
/**
 * System REST API
 *  This page provides documentation for the System REST API.  If you have any questions or need support, please contact us at the email provided.  ## Formatting query parameters  Filters should be formatted as `field:value` and use the logical OR operator `||` to specify an OR condition. (We\'ve deprecated the pipe operator for OR conditions.)   If they are numerical, they should be formatted as `field:opvalue`. Examples: - `doi:10.1234/5678||10.8765/4321` - `num_findings:>2`  Sorts should be formatted as `field:direction`. Examples: - `cited_by:desc` - `publish_date:asc`  Searches should be formatted as `field:value`. Examples: - `name:osteoporosis` 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: api@system.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GuidelinePollingStatus } from './GuidelinePollingStatus';
import {
    GuidelinePollingStatusFromJSON,
    GuidelinePollingStatusFromJSONTyped,
    GuidelinePollingStatusToJSON,
} from './GuidelinePollingStatus';
import type { GuidelineSynthesis } from './GuidelineSynthesis';
import {
    GuidelineSynthesisFromJSON,
    GuidelineSynthesisFromJSONTyped,
    GuidelineSynthesisToJSON,
} from './GuidelineSynthesis';

/**
 * Synthesis fetching output schema.
 * @export
 * @interface GuidelineSynthesisOut
 */
export interface GuidelineSynthesisOut {
    /**
     * 
     * @type {GuidelinePollingStatus}
     * @memberof GuidelineSynthesisOut
     */
    status: GuidelinePollingStatus;
    /**
     * 
     * @type {GuidelineSynthesis}
     * @memberof GuidelineSynthesisOut
     */
    synthesis: GuidelineSynthesis | null;
}

/**
 * Check if a given object implements the GuidelineSynthesisOut interface.
 */
export function instanceOfGuidelineSynthesisOut(value: object): value is GuidelineSynthesisOut {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('synthesis' in value) || value['synthesis'] === undefined) return false;
    return true;
}

export function GuidelineSynthesisOutFromJSON(json: any): GuidelineSynthesisOut {
    return GuidelineSynthesisOutFromJSONTyped(json, false);
}

export function GuidelineSynthesisOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): GuidelineSynthesisOut {
    if (json == null) {
        return json;
    }
    return {
        
        'status': GuidelinePollingStatusFromJSON(json['status']),
        'synthesis': GuidelineSynthesisFromJSON(json['synthesis']),
    };
}

export function GuidelineSynthesisOutToJSON(value?: GuidelineSynthesisOut | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'status': GuidelinePollingStatusToJSON(value['status']),
        'synthesis': GuidelineSynthesisToJSON(value['synthesis']),
    };
}

