/* tslint:disable */
/* eslint-disable */
/**
 * System REST API
 *  This page provides documentation for the System REST API.  If you have any questions or need support, please contact us at the email provided.  ## Formatting query parameters  Filters should be formatted as `field:value` and use the logical OR operator `||` to specify an OR condition. (We\'ve deprecated the pipe operator for OR conditions.)   If they are numerical, they should be formatted as `field:opvalue`. Examples: - `doi:10.1234/5678||10.8765/4321` - `num_findings:>2`  Sorts should be formatted as `field:direction`. Examples: - `cited_by:desc` - `publish_date:asc`  Searches should be formatted as `field:value`. Examples: - `name:osteoporosis` 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: api@system.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Reference } from './Reference';
import {
    ReferenceFromJSON,
    ReferenceFromJSONTyped,
    ReferenceToJSON,
} from './Reference';

/**
 * GuidelineSynthesis
 * @export
 * @interface GuidelineSynthesis
 */
export interface GuidelineSynthesis {
    /**
     * 
     * @type {string}
     * @memberof GuidelineSynthesis
     */
    synthesis: string;
    /**
     * 
     * @type {Array<Reference>}
     * @memberof GuidelineSynthesis
     */
    reference: Array<Reference>;
    /**
     * 
     * @type {string}
     * @memberof GuidelineSynthesis
     */
    status: string;
}

/**
 * Check if a given object implements the GuidelineSynthesis interface.
 */
export function instanceOfGuidelineSynthesis(value: object): value is GuidelineSynthesis {
    if (!('synthesis' in value) || value['synthesis'] === undefined) return false;
    if (!('reference' in value) || value['reference'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function GuidelineSynthesisFromJSON(json: any): GuidelineSynthesis {
    return GuidelineSynthesisFromJSONTyped(json, false);
}

export function GuidelineSynthesisFromJSONTyped(json: any, ignoreDiscriminator: boolean): GuidelineSynthesis {
    if (json == null) {
        return json;
    }
    return {
        
        'synthesis': json['synthesis'],
        'reference': ((json['reference'] as Array<any>).map(ReferenceFromJSON)),
        'status': json['status'],
    };
}

export function GuidelineSynthesisToJSON(value?: GuidelineSynthesis | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'synthesis': value['synthesis'],
        'reference': ((value['reference'] as Array<any>).map(ReferenceToJSON)),
        'status': value['status'],
    };
}

