/* tslint:disable */
/* eslint-disable */
/**
 * System REST API
 *  This page provides documentation for the System REST API.  If you have any questions or need support, please contact us at the email provided.  ## Formatting query parameters  Filters should be formatted as `field:value` and use the logical OR operator `||` to specify an OR condition. (We\'ve deprecated the pipe operator for OR conditions.)   If they are numerical, they should be formatted as `field:opvalue`. Examples: - `doi:10.1234/5678||10.8765/4321` - `num_findings:>2`  Sorts should be formatted as `field:direction`. Examples: - `cited_by:desc` - `publish_date:asc`  Searches should be formatted as `field:value`. Examples: - `name:osteoporosis` 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: api@system.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Polling status enum.
 * @export
 */
export const GuidelinePollingStatus = {
    NotExists: 'not_exists',
    Submitted: 'submitted',
    Running: 'running',
    Success: 'success',
    Failed: 'failed'
} as const;
export type GuidelinePollingStatus = typeof GuidelinePollingStatus[keyof typeof GuidelinePollingStatus];


export function instanceOfGuidelinePollingStatus(value: any): boolean {
    for (const key in GuidelinePollingStatus) {
        if (Object.prototype.hasOwnProperty.call(GuidelinePollingStatus, key)) {
            if ((GuidelinePollingStatus as Record<string, GuidelinePollingStatus>)[key] === value) {
                return true;
            }
        }
    }
    return false;
}

export function GuidelinePollingStatusFromJSON(json: any): GuidelinePollingStatus {
    return GuidelinePollingStatusFromJSONTyped(json, false);
}

export function GuidelinePollingStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): GuidelinePollingStatus {
    return json as GuidelinePollingStatus;
}

export function GuidelinePollingStatusToJSON(value?: GuidelinePollingStatus | null): any {
    return value as any;
}

