/* tslint:disable */
/* eslint-disable */
/**
 * System REST API
 *  This page provides documentation for the System REST API.  If you have any questions or need support, please contact us at the email provided.  ## Formatting query parameters  Filters should be formatted as `field:value` and use the logical OR operator `||` to specify an OR condition. (We\'ve deprecated the pipe operator for OR conditions.)   If they are numerical, they should be formatted as `field:opvalue`. Examples: - `doi:10.1234/5678||10.8765/4321` - `num_findings:>2`  Sorts should be formatted as `field:direction`. Examples: - `cited_by:desc` - `publish_date:asc`  Searches should be formatted as `field:value`. Examples: - `name:osteoporosis` 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: api@system.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Payload to kickoff synthesis generation.
 * @export
 * @interface GuidelineSynthesisIn
 */
export interface GuidelineSynthesisIn {
    /**
     * User query.
     * @type {string}
     * @memberof GuidelineSynthesisIn
     */
    userQuery: string;
}

/**
 * Check if a given object implements the GuidelineSynthesisIn interface.
 */
export function instanceOfGuidelineSynthesisIn(value: object): value is GuidelineSynthesisIn {
    if (!('userQuery' in value) || value['userQuery'] === undefined) return false;
    return true;
}

export function GuidelineSynthesisInFromJSON(json: any): GuidelineSynthesisIn {
    return GuidelineSynthesisInFromJSONTyped(json, false);
}

export function GuidelineSynthesisInFromJSONTyped(json: any, ignoreDiscriminator: boolean): GuidelineSynthesisIn {
    if (json == null) {
        return json;
    }
    return {
        
        'userQuery': json['user_query'],
    };
}

export function GuidelineSynthesisInToJSON(value?: GuidelineSynthesisIn | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'user_query': value['userQuery'],
    };
}

