/* tslint:disable */
/* eslint-disable */
/**
 * System REST API
 *  This page provides documentation for the System REST API.  If you have any questions or need support, please contact us at the email provided.  ## Formatting query parameters  Filters should be formatted as `field:value` and use the logical OR operator `||` to specify an OR condition. (We\'ve deprecated the pipe operator for OR conditions.)   If they are numerical, they should be formatted as `field:opvalue`. Examples: - `doi:10.1234/5678||10.8765/4321` - `num_findings:>2`  Sorts should be formatted as `field:direction`. Examples: - `cited_by:desc` - `publish_date:asc`  Searches should be formatted as `field:value`. Examples: - `name:osteoporosis` 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: api@system.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Status of a pubmed search synthesis job.
 * @export
 */
export const JobStatus = {
    Accepted: 'accepted',
    Clustering: 'clustering',
    ClusteringFailed: 'clustering_failed',
    ClusteringFailedNoClusters: 'clustering_failed_no_clusters',
    Synthesizing: 'synthesizing',
    SynthesisNotExists: 'synthesis_not_exists',
    SynthesisSubmitted: 'synthesis_submitted',
    SynthesisRunning: 'synthesis_running',
    SynthesisSuccess: 'synthesis_success',
    SynthesisFailed: 'synthesis_failed',
    SynthesisFailedNoCitations: 'synthesis_failed_no_citations',
    SynthesisFailedValidation: 'synthesis_failed_validation'
} as const;
export type JobStatus = typeof JobStatus[keyof typeof JobStatus];


export function instanceOfJobStatus(value: any): boolean {
    for (const key in JobStatus) {
        if (Object.prototype.hasOwnProperty.call(JobStatus, key)) {
            if ((JobStatus as Record<string, JobStatus>)[key] === value) {
                return true;
            }
        }
    }
    return false;
}

export function JobStatusFromJSON(json: any): JobStatus {
    return JobStatusFromJSONTyped(json, false);
}

export function JobStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobStatus {
    return json as JobStatus;
}

export function JobStatusToJSON(value?: JobStatus | null): any {
    return value as any;
}

