/* tslint:disable */
/* eslint-disable */
/**
 * System REST API
 *  This page provides documentation for the System REST API.  If you have any questions or need support, please contact us at the email provided.  ## Formatting query parameters  Filters should be formatted as `field:value` and use the logical OR operator `||` to specify an OR condition. (We\'ve deprecated the pipe operator for OR conditions.)   If they are numerical, they should be formatted as `field:opvalue`. Examples: - `doi:10.1234/5678||10.8765/4321` - `num_findings:>2`  Sorts should be formatted as `field:direction`. Examples: - `cited_by:desc` - `publish_date:asc`  Searches should be formatted as `field:value`. Examples: - `name:osteoporosis` 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: api@system.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TopicPath } from './TopicPath';
import {
    TopicPathFromJSON,
    TopicPathFromJSONTyped,
    TopicPathToJSON,
} from './TopicPath';

/**
 * 
 * @export
 * @interface ListResponseTopicPath
 */
export interface ListResponseTopicPath {
    /**
     * 
     * @type {Array<TopicPath>}
     * @memberof ListResponseTopicPath
     */
    data: Array<TopicPath>;
    /**
     * 
     * @type {number}
     * @memberof ListResponseTopicPath
     */
    total?: number | null;
}

/**
 * Check if a given object implements the ListResponseTopicPath interface.
 */
export function instanceOfListResponseTopicPath(value: object): value is ListResponseTopicPath {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function ListResponseTopicPathFromJSON(json: any): ListResponseTopicPath {
    return ListResponseTopicPathFromJSONTyped(json, false);
}

export function ListResponseTopicPathFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListResponseTopicPath {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(TopicPathFromJSON)),
        'total': json['total'] == null ? undefined : json['total'],
    };
}

export function ListResponseTopicPathToJSON(value?: ListResponseTopicPath | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data': ((value['data'] as Array<any>).map(TopicPathToJSON)),
        'total': value['total'],
    };
}

