/* tslint:disable */
/* eslint-disable */
/**
 * System REST API
 *  This page provides documentation for the System REST API.  If you have any questions or need support, please contact us at the email provided.  ## Formatting query parameters  Filters should be formatted as `field:value` and use the logical OR operator `||` to specify an OR condition. (We\'ve deprecated the pipe operator for OR conditions.)   If they are numerical, they should be formatted as `field:opvalue`. Examples: - `doi:10.1234/5678||10.8765/4321` - `num_findings:>2`  Sorts should be formatted as `field:direction`. Examples: - `cited_by:desc` - `publish_date:asc`  Searches should be formatted as `field:value`. Examples: - `name:osteoporosis` 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: api@system.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StatementScore } from './StatementScore';
import {
    StatementScoreFromJSON,
    StatementScoreFromJSONTyped,
    StatementScoreToJSON,
} from './StatementScore';

/**
 * 
 * @export
 * @interface ListResponseStatementScore
 */
export interface ListResponseStatementScore {
    /**
     * 
     * @type {Array<StatementScore>}
     * @memberof ListResponseStatementScore
     */
    data: Array<StatementScore>;
    /**
     * 
     * @type {number}
     * @memberof ListResponseStatementScore
     */
    total?: number | null;
}

/**
 * Check if a given object implements the ListResponseStatementScore interface.
 */
export function instanceOfListResponseStatementScore(value: object): value is ListResponseStatementScore {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function ListResponseStatementScoreFromJSON(json: any): ListResponseStatementScore {
    return ListResponseStatementScoreFromJSONTyped(json, false);
}

export function ListResponseStatementScoreFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListResponseStatementScore {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(StatementScoreFromJSON)),
        'total': json['total'] == null ? undefined : json['total'],
    };
}

export function ListResponseStatementScoreToJSON(value?: ListResponseStatementScore | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data': ((value['data'] as Array<any>).map(StatementScoreToJSON)),
        'total': value['total'],
    };
}

