/* tslint:disable */
/* eslint-disable */
/**
 * System REST API
 *  This page provides documentation for the System REST API.  If you have any questions or need support, please contact us at the email provided.  ## Formatting query parameters  Filters should be formatted as `field:value` and use the logical OR operator `||` to specify an OR condition. (We\'ve deprecated the pipe operator for OR conditions.)   If they are numerical, they should be formatted as `field:opvalue`. Examples: - `doi:10.1234/5678||10.8765/4321` - `num_findings:>2`  Sorts should be formatted as `field:direction`. Examples: - `cited_by:desc` - `publish_date:asc`  Searches should be formatted as `field:value`. Examples: - `name:osteoporosis` 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: api@system.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Relationship } from './Relationship';
import {
    RelationshipFromJSON,
    RelationshipFromJSONTyped,
    RelationshipToJSON,
} from './Relationship';

/**
 * 
 * @export
 * @interface ListResponseRelationship
 */
export interface ListResponseRelationship {
    /**
     * 
     * @type {Array<Relationship>}
     * @memberof ListResponseRelationship
     */
    data: Array<Relationship>;
    /**
     * 
     * @type {number}
     * @memberof ListResponseRelationship
     */
    total?: number | null;
}

/**
 * Check if a given object implements the ListResponseRelationship interface.
 */
export function instanceOfListResponseRelationship(value: object): value is ListResponseRelationship {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function ListResponseRelationshipFromJSON(json: any): ListResponseRelationship {
    return ListResponseRelationshipFromJSONTyped(json, false);
}

export function ListResponseRelationshipFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListResponseRelationship {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(RelationshipFromJSON)),
        'total': json['total'] == null ? undefined : json['total'],
    };
}

export function ListResponseRelationshipToJSON(value?: ListResponseRelationship | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data': ((value['data'] as Array<any>).map(RelationshipToJSON)),
        'total': value['total'],
    };
}

