/* tslint:disable */
/* eslint-disable */
/**
 * System REST API
 *  This page provides documentation for the System REST API.  If you have any questions or need support, please contact us at the email provided.  ## Formatting query parameters  Filters should be formatted as `field:value` and use the logical OR operator `||` to specify an OR condition. (We\'ve deprecated the pipe operator for OR conditions.)   If they are numerical, they should be formatted as `field:opvalue`. Examples: - `doi:10.1234/5678||10.8765/4321` - `num_findings:>2`  Sorts should be formatted as `field:direction`. Examples: - `cited_by:desc` - `publish_date:asc`  Searches should be formatted as `field:value`. Examples: - `name:osteoporosis` 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: api@system.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Variable } from './Variable';
import {
    VariableFromJSON,
    VariableFromJSONTyped,
    VariableToJSON,
} from './Variable';

/**
 * 
 * @export
 * @interface ListResponseVariable
 */
export interface ListResponseVariable {
    /**
     * 
     * @type {Array<Variable>}
     * @memberof ListResponseVariable
     */
    data: Array<Variable>;
    /**
     * 
     * @type {number}
     * @memberof ListResponseVariable
     */
    total?: number | null;
}

/**
 * Check if a given object implements the ListResponseVariable interface.
 */
export function instanceOfListResponseVariable(value: object): value is ListResponseVariable {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function ListResponseVariableFromJSON(json: any): ListResponseVariable {
    return ListResponseVariableFromJSONTyped(json, false);
}

export function ListResponseVariableFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListResponseVariable {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(VariableFromJSON)),
        'total': json['total'] == null ? undefined : json['total'],
    };
}

export function ListResponseVariableToJSON(value?: ListResponseVariable | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data': ((value['data'] as Array<any>).map(VariableToJSON)),
        'total': value['total'],
    };
}

