/* tslint:disable */
/* eslint-disable */
/**
 * System REST API
 *  This page provides documentation for the System REST API.  If you have any questions or need support, please contact us at the email provided.  ## Formatting query parameters  Filters should be formatted as `field:value` and use the logical OR operator `||` to specify an OR condition. (We\'ve deprecated the pipe operator for OR conditions.)   If they are numerical, they should be formatted as `field:opvalue`. Examples: - `doi:10.1234/5678||10.8765/4321` - `num_findings:>2`  Sorts should be formatted as `field:direction`. Examples: - `cited_by:desc` - `publish_date:asc`  Searches should be formatted as `field:value`. Examples: - `name:osteoporosis` 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: api@system.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Study } from './Study';
import {
    StudyFromJSON,
    StudyFromJSONTyped,
    StudyToJSON,
} from './Study';
import type { Variable } from './Variable';
import {
    VariableFromJSON,
    VariableFromJSONTyped,
    VariableToJSON,
} from './Variable';
import type { MechanismType } from './MechanismType';
import {
    MechanismTypeFromJSON,
    MechanismTypeFromJSONTyped,
    MechanismTypeToJSON,
} from './MechanismType';
import type { Topic } from './Topic';
import {
    TopicFromJSON,
    TopicFromJSONTyped,
    TopicToJSON,
} from './Topic';

/**
 * Mechanistic finding.
 * @export
 * @interface MechanisticFinding
 */
export interface MechanisticFinding {
    /**
     * Unique identifier
     * @type {string}
     * @memberof MechanisticFinding
     */
    id: string;
    /**
     * Whether finding is flagged
     * @type {boolean}
     * @memberof MechanisticFinding
     */
    flagged?: boolean;
    /**
     * Type of finding
     * @type {string}
     * @memberof MechanisticFinding
     */
    findingType?: MechanisticFindingFindingTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof MechanisticFinding
     */
    summary?: string | null;
    /**
     * 
     * @type {Topic}
     * @memberof MechanisticFinding
     */
    topic1?: Topic | null;
    /**
     * 
     * @type {Topic}
     * @memberof MechanisticFinding
     */
    topic2?: Topic | null;
    /**
     * Source variable of the finding
     * @type {Variable}
     * @memberof MechanisticFinding
     */
    variable1?: Variable;
    /**
     * Target variable of the finding
     * @type {Variable}
     * @memberof MechanisticFinding
     */
    variable2?: Variable;
    /**
     * Study supporting the finding
     * @type {Study}
     * @memberof MechanisticFinding
     */
    study?: Study;
    /**
     * 
     * @type {MechanismType}
     * @memberof MechanisticFinding
     */
    mechanismType?: MechanismType | null;
}


/**
 * @export
 */
export const MechanisticFindingFindingTypeEnum = {
    Mechanistic: 'mechanistic'
} as const;
export type MechanisticFindingFindingTypeEnum = typeof MechanisticFindingFindingTypeEnum[keyof typeof MechanisticFindingFindingTypeEnum];


/**
 * Check if a given object implements the MechanisticFinding interface.
 */
export function instanceOfMechanisticFinding(value: object): value is MechanisticFinding {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function MechanisticFindingFromJSON(json: any): MechanisticFinding {
    return MechanisticFindingFromJSONTyped(json, false);
}

export function MechanisticFindingFromJSONTyped(json: any, ignoreDiscriminator: boolean): MechanisticFinding {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'flagged': json['flagged'] == null ? undefined : json['flagged'],
        'findingType': json['finding_type'] == null ? undefined : json['finding_type'],
        'summary': json['summary'] == null ? undefined : json['summary'],
        'topic1': json['topic_1'] == null ? undefined : TopicFromJSON(json['topic_1']),
        'topic2': json['topic_2'] == null ? undefined : TopicFromJSON(json['topic_2']),
        'variable1': json['variable_1'] == null ? undefined : VariableFromJSON(json['variable_1']),
        'variable2': json['variable_2'] == null ? undefined : VariableFromJSON(json['variable_2']),
        'study': json['study'] == null ? undefined : StudyFromJSON(json['study']),
        'mechanismType': json['mechanism_type'] == null ? undefined : MechanismTypeFromJSON(json['mechanism_type']),
    };
}

export function MechanisticFindingToJSON(value?: MechanisticFinding | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'flagged': value['flagged'],
        'finding_type': value['findingType'],
        'summary': value['summary'],
        'topic_1': TopicToJSON(value['topic1']),
        'topic_2': TopicToJSON(value['topic2']),
        'variable_1': VariableToJSON(value['variable1']),
        'variable_2': VariableToJSON(value['variable2']),
        'study': StudyToJSON(value['study']),
        'mechanism_type': MechanismTypeToJSON(value['mechanismType']),
    };
}

