/* tslint:disable */
/* eslint-disable */
/**
 * System REST API
 *  This page provides documentation for the System REST API.  If you have any questions or need support, please contact us at the email provided.  ## Formatting query parameters  Filters should be formatted as `field:value` and use the logical OR operator `||` to specify an OR condition. (We\'ve deprecated the pipe operator for OR conditions.)   If they are numerical, they should be formatted as `field:opvalue`. Examples: - `doi:10.1234/5678||10.8765/4321` - `num_findings:>2`  Sorts should be formatted as `field:direction`. Examples: - `cited_by:desc` - `publish_date:asc`  Searches should be formatted as `field:value`. Examples: - `name:osteoporosis` 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: api@system.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Nested study.
 * @export
 * @interface NestedStudy
 */
export interface NestedStudy {
    /**
     * Unique identifier
     * @type {string}
     * @memberof NestedStudy
     */
    id: string;
    /**
     * Digital Object Identifier (DOI)
     * @type {string}
     * @memberof NestedStudy
     */
    doi?: string;
    /**
     * Population studied
     * @type {string}
     * @memberof NestedStudy
     */
    population?: string;
    /**
     * Sample size of the study
     * @type {string}
     * @memberof NestedStudy
     */
    sampleSize?: string;
}

/**
 * Check if a given object implements the NestedStudy interface.
 */
export function instanceOfNestedStudy(value: object): value is NestedStudy {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function NestedStudyFromJSON(json: any): NestedStudy {
    return NestedStudyFromJSONTyped(json, false);
}

export function NestedStudyFromJSONTyped(json: any, ignoreDiscriminator: boolean): NestedStudy {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'doi': json['doi'] == null ? undefined : json['doi'],
        'population': json['population'] == null ? undefined : json['population'],
        'sampleSize': json['sample_size'] == null ? undefined : json['sample_size'],
    };
}

export function NestedStudyToJSON(value?: NestedStudy | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'doi': value['doi'],
        'population': value['population'],
        'sample_size': value['sampleSize'],
    };
}

