/* tslint:disable */
/* eslint-disable */
/**
 * System REST API
 *  This page provides documentation for the System REST API.  If you have any questions or need support, please contact us at the email provided.  ## Formatting query parameters  Filters should be formatted as `field:value` and use the logical OR operator `||` to specify an OR condition. (We\'ve deprecated the pipe operator for OR conditions.)   If they are numerical, they should be formatted as `field:opvalue`. Examples: - `doi:10.1234/5678||10.8765/4321` - `num_findings:>2`  Sorts should be formatted as `field:direction`. Examples: - `cited_by:desc` - `publish_date:asc`  Searches should be formatted as `field:value`. Examples: - `name:osteoporosis` 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: api@system.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostCypherRecordsData
 */
export interface PostCypherRecordsData {
    /**
     * 
     * @type {string}
     * @memberof PostCypherRecordsData
     */
    type: PostCypherRecordsDataTypeEnum;
    /**
     * 
     * @type {Array<object>}
     * @memberof PostCypherRecordsData
     */
    content: Array<object>;
}


/**
 * @export
 */
export const PostCypherRecordsDataTypeEnum = {
    Records: 'records'
} as const;
export type PostCypherRecordsDataTypeEnum = typeof PostCypherRecordsDataTypeEnum[keyof typeof PostCypherRecordsDataTypeEnum];


/**
 * Check if a given object implements the PostCypherRecordsData interface.
 */
export function instanceOfPostCypherRecordsData(value: object): value is PostCypherRecordsData {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    return true;
}

export function PostCypherRecordsDataFromJSON(json: any): PostCypherRecordsData {
    return PostCypherRecordsDataFromJSONTyped(json, false);
}

export function PostCypherRecordsDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostCypherRecordsData {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'content': json['content'],
    };
}

export function PostCypherRecordsDataToJSON(value?: PostCypherRecordsData | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'type': value['type'],
        'content': value['content'],
    };
}

