/* tslint:disable */
/* eslint-disable */
/**
 * System REST API
 *  This page provides documentation for the System REST API.  If you have any questions or need support, please contact us at the email provided.  ## Formatting query parameters  Filters should be formatted as `field:value` and use the logical OR operator `||` to specify an OR condition. (We\'ve deprecated the pipe operator for OR conditions.)   If they are numerical, they should be formatted as `field:opvalue`. Examples: - `doi:10.1234/5678||10.8765/4321` - `num_findings:>2`  Sorts should be formatted as `field:direction`. Examples: - `cited_by:desc` - `publish_date:asc`  Searches should be formatted as `field:value`. Examples: - `name:osteoporosis` 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: api@system.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Pubmed search translation input.
 * @export
 * @interface PubmedSearchTranslationInput
 */
export interface PubmedSearchTranslationInput {
    /**
     * 
     * @type {string}
     * @memberof PubmedSearchTranslationInput
     */
    query: string;
}

/**
 * Check if a given object implements the PubmedSearchTranslationInput interface.
 */
export function instanceOfPubmedSearchTranslationInput(value: object): value is PubmedSearchTranslationInput {
    if (!('query' in value) || value['query'] === undefined) return false;
    return true;
}

export function PubmedSearchTranslationInputFromJSON(json: any): PubmedSearchTranslationInput {
    return PubmedSearchTranslationInputFromJSONTyped(json, false);
}

export function PubmedSearchTranslationInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): PubmedSearchTranslationInput {
    if (json == null) {
        return json;
    }
    return {
        
        'query': json['query'],
    };
}

export function PubmedSearchTranslationInputToJSON(value?: PubmedSearchTranslationInput | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'query': value['query'],
    };
}

