/* tslint:disable */
/* eslint-disable */
/**
 * System REST API
 *  This page provides documentation for the System REST API.  If you have any questions or need support, please contact us at the email provided.  ## Formatting query parameters  Filters should be formatted as `field:value` and use the logical OR operator `||` to specify an OR condition. (We\'ve deprecated the pipe operator for OR conditions.)   If they are numerical, they should be formatted as `field:opvalue`. Examples: - `doi:10.1234/5678||10.8765/4321` - `num_findings:>2`  Sorts should be formatted as `field:direction`. Examples: - `cited_by:desc` - `publish_date:asc`  Searches should be formatted as `field:value`. Examples: - `name:osteoporosis` 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: api@system.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Sign
 */
export interface Sign {
    /**
     * 
     * @type {string}
     * @memberof Sign
     */
    rationale: string;
    /**
     * 
     * @type {string}
     * @memberof Sign
     */
    sign: string;
}

/**
 * Check if a given object implements the Sign interface.
 */
export function instanceOfSign(value: object): value is Sign {
    if (!('rationale' in value) || value['rationale'] === undefined) return false;
    if (!('sign' in value) || value['sign'] === undefined) return false;
    return true;
}

export function SignFromJSON(json: any): Sign {
    return SignFromJSONTyped(json, false);
}

export function SignFromJSONTyped(json: any, ignoreDiscriminator: boolean): Sign {
    if (json == null) {
        return json;
    }
    return {
        
        'rationale': json['rationale'],
        'sign': json['sign'],
    };
}

export function SignToJSON(value?: Sign | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'rationale': value['rationale'],
        'sign': value['sign'],
    };
}

