/* tslint:disable */
/* eslint-disable */
/**
 * System REST API
 *  This page provides documentation for the System REST API.  If you have any questions or need support, please contact us at the email provided.  ## Formatting query parameters  Filters should be formatted as `field:value` and use the logical OR operator `||` to specify an OR condition. (We\'ve deprecated the pipe operator for OR conditions.)   If they are numerical, they should be formatted as `field:opvalue`. Examples: - `doi:10.1234/5678||10.8765/4321` - `num_findings:>2`  Sorts should be formatted as `field:direction`. Examples: - `cited_by:desc` - `publish_date:asc`  Searches should be formatted as `field:value`. Examples: - `name:osteoporosis` 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: api@system.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Statement relevancy score with reasoning.
 * @export
 * @interface StatementScore
 */
export interface StatementScore {
    /**
     * 
     * @type {string}
     * @memberof StatementScore
     */
    statement?: string | null;
    /**
     * 
     * @type {number}
     * @memberof StatementScore
     */
    score?: number | null;
    /**
     * 
     * @type {string}
     * @memberof StatementScore
     */
    reasoning?: string | null;
}

/**
 * Check if a given object implements the StatementScore interface.
 */
export function instanceOfStatementScore(value: object): value is StatementScore {
    return true;
}

export function StatementScoreFromJSON(json: any): StatementScore {
    return StatementScoreFromJSONTyped(json, false);
}

export function StatementScoreFromJSONTyped(json: any, ignoreDiscriminator: boolean): StatementScore {
    if (json == null) {
        return json;
    }
    return {
        
        'statement': json['statement'] == null ? undefined : json['statement'],
        'score': json['score'] == null ? undefined : json['score'],
        'reasoning': json['reasoning'] == null ? undefined : json['reasoning'],
    };
}

export function StatementScoreToJSON(value?: StatementScore | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'statement': value['statement'],
        'score': value['score'],
        'reasoning': value['reasoning'],
    };
}

