/* tslint:disable */
/* eslint-disable */
/**
 * System REST API
 *  This page provides documentation for the System REST API.  If you have any questions or need support, please contact us at the email provided.  ## Formatting query parameters  Filters should be formatted as `field:value` and use the logical OR operator `||` to specify an OR condition. (We\'ve deprecated the pipe operator for OR conditions.)   If they are numerical, they should be formatted as `field:opvalue`. Examples: - `doi:10.1234/5678||10.8765/4321` - `num_findings:>2`  Sorts should be formatted as `field:direction`. Examples: - `cited_by:desc` - `publish_date:asc`  Searches should be formatted as `field:value`. Examples: - `name:osteoporosis` 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: api@system.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FindingType } from './FindingType';
import {
    FindingTypeFromJSON,
    FindingTypeFromJSONTyped,
    FindingTypeToJSON,
} from './FindingType';

/**
 * Statements generated from aggregated findings.
 * @export
 * @interface Statement
 */
export interface Statement {
    /**
     * 
     * @type {string}
     * @memberof Statement
     */
    summary: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof Statement
     */
    findingIds: Array<string>;
    /**
     * 
     * @type {FindingType}
     * @memberof Statement
     */
    findingType: FindingType;
}

/**
 * Check if a given object implements the Statement interface.
 */
export function instanceOfStatement(value: object): value is Statement {
    if (!('summary' in value) || value['summary'] === undefined) return false;
    if (!('findingIds' in value) || value['findingIds'] === undefined) return false;
    if (!('findingType' in value) || value['findingType'] === undefined) return false;
    return true;
}

export function StatementFromJSON(json: any): Statement {
    return StatementFromJSONTyped(json, false);
}

export function StatementFromJSONTyped(json: any, ignoreDiscriminator: boolean): Statement {
    if (json == null) {
        return json;
    }
    return {
        
        'summary': json['summary'],
        'findingIds': json['finding_ids'],
        'findingType': FindingTypeFromJSON(json['finding_type']),
    };
}

export function StatementToJSON(value?: Statement | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'summary': value['summary'],
        'finding_ids': value['findingIds'],
        'finding_type': FindingTypeToJSON(value['findingType']),
    };
}

