/* tslint:disable */
/* eslint-disable */
/**
 * System REST API
 *  This page provides documentation for the System REST API.  If you have any questions or need support, please contact us at the email provided.  ## Formatting query parameters  Filters should be formatted as `field:value` and use the logical OR operator `||` to specify an OR condition. (We\'ve deprecated the pipe operator for OR conditions.)   If they are numerical, they should be formatted as `field:opvalue`. Examples: - `doi:10.1234/5678||10.8765/4321` - `num_findings:>2`  Sorts should be formatted as `field:direction`. Examples: - `cited_by:desc` - `publish_date:asc`  Searches should be formatted as `field:value`. Examples: - `name:osteoporosis` 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: api@system.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Study } from './Study';
import {
    StudyFromJSON,
    StudyFromJSONTyped,
    StudyToJSON,
} from './Study';
import type { Variable } from './Variable';
import {
    VariableFromJSON,
    VariableFromJSONTyped,
    VariableToJSON,
} from './Variable';
import type { StatisticType } from './StatisticType';
import {
    StatisticTypeFromJSON,
    StatisticTypeFromJSONTyped,
    StatisticTypeToJSON,
} from './StatisticType';
import type { Topic } from './Topic';
import {
    TopicFromJSON,
    TopicFromJSONTyped,
    TopicToJSON,
} from './Topic';

/**
 * Statistical finding.
 * @export
 * @interface StatisticalFinding
 */
export interface StatisticalFinding {
    /**
     * Unique identifier
     * @type {string}
     * @memberof StatisticalFinding
     */
    id: string;
    /**
     * Whether finding is flagged
     * @type {boolean}
     * @memberof StatisticalFinding
     */
    flagged?: boolean;
    /**
     * Type of finding
     * @type {string}
     * @memberof StatisticalFinding
     */
    findingType?: StatisticalFindingFindingTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof StatisticalFinding
     */
    summary?: string | null;
    /**
     * 
     * @type {Topic}
     * @memberof StatisticalFinding
     */
    topic1?: Topic | null;
    /**
     * 
     * @type {Topic}
     * @memberof StatisticalFinding
     */
    topic2?: Topic | null;
    /**
     * Source variable of the finding
     * @type {Variable}
     * @memberof StatisticalFinding
     */
    variable1?: Variable;
    /**
     * Target variable of the finding
     * @type {Variable}
     * @memberof StatisticalFinding
     */
    variable2?: Variable;
    /**
     * Study supporting the finding
     * @type {Study}
     * @memberof StatisticalFinding
     */
    study?: Study;
    /**
     * 
     * @type {StatisticType}
     * @memberof StatisticalFinding
     */
    statisticType?: StatisticType | null;
    /**
     * 
     * @type {number}
     * @memberof StatisticalFinding
     */
    statisticValue?: number | null;
    /**
     * 
     * @type {number}
     * @memberof StatisticalFinding
     */
    effectSize?: number | null;
    /**
     * 
     * @type {number}
     * @memberof StatisticalFinding
     */
    ciUpper?: number | null;
    /**
     * 
     * @type {number}
     * @memberof StatisticalFinding
     */
    ciLower?: number | null;
    /**
     * 
     * @type {number}
     * @memberof StatisticalFinding
     */
    pValue?: number | null;
}


/**
 * @export
 */
export const StatisticalFindingFindingTypeEnum = {
    Statistical: 'statistical'
} as const;
export type StatisticalFindingFindingTypeEnum = typeof StatisticalFindingFindingTypeEnum[keyof typeof StatisticalFindingFindingTypeEnum];


/**
 * Check if a given object implements the StatisticalFinding interface.
 */
export function instanceOfStatisticalFinding(value: object): value is StatisticalFinding {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function StatisticalFindingFromJSON(json: any): StatisticalFinding {
    return StatisticalFindingFromJSONTyped(json, false);
}

export function StatisticalFindingFromJSONTyped(json: any, ignoreDiscriminator: boolean): StatisticalFinding {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'flagged': json['flagged'] == null ? undefined : json['flagged'],
        'findingType': json['finding_type'] == null ? undefined : json['finding_type'],
        'summary': json['summary'] == null ? undefined : json['summary'],
        'topic1': json['topic_1'] == null ? undefined : TopicFromJSON(json['topic_1']),
        'topic2': json['topic_2'] == null ? undefined : TopicFromJSON(json['topic_2']),
        'variable1': json['variable_1'] == null ? undefined : VariableFromJSON(json['variable_1']),
        'variable2': json['variable_2'] == null ? undefined : VariableFromJSON(json['variable_2']),
        'study': json['study'] == null ? undefined : StudyFromJSON(json['study']),
        'statisticType': json['statistic_type'] == null ? undefined : StatisticTypeFromJSON(json['statistic_type']),
        'statisticValue': json['statistic_value'] == null ? undefined : json['statistic_value'],
        'effectSize': json['effect_size'] == null ? undefined : json['effect_size'],
        'ciUpper': json['ci_upper'] == null ? undefined : json['ci_upper'],
        'ciLower': json['ci_lower'] == null ? undefined : json['ci_lower'],
        'pValue': json['p_value'] == null ? undefined : json['p_value'],
    };
}

export function StatisticalFindingToJSON(value?: StatisticalFinding | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'flagged': value['flagged'],
        'finding_type': value['findingType'],
        'summary': value['summary'],
        'topic_1': TopicToJSON(value['topic1']),
        'topic_2': TopicToJSON(value['topic2']),
        'variable_1': VariableToJSON(value['variable1']),
        'variable_2': VariableToJSON(value['variable2']),
        'study': StudyToJSON(value['study']),
        'statistic_type': StatisticTypeToJSON(value['statisticType']),
        'statistic_value': value['statisticValue'],
        'effect_size': value['effectSize'],
        'ci_upper': value['ciUpper'],
        'ci_lower': value['ciLower'],
        'p_value': value['pValue'],
    };
}

