/* tslint:disable */
/* eslint-disable */
/**
 * System REST API
 *  This page provides documentation for the System REST API.  If you have any questions or need support, please contact us at the email provided.  ## Formatting query parameters  Filters should be formatted as `field:value` and use the logical OR operator `||` to specify an OR condition. (We\'ve deprecated the pipe operator for OR conditions.)   If they are numerical, they should be formatted as `field:opvalue`. Examples: - `doi:10.1234/5678||10.8765/4321` - `num_findings:>2`  Sorts should be formatted as `field:direction`. Examples: - `cited_by:desc` - `publish_date:asc`  Searches should be formatted as `field:value`. Examples: - `name:osteoporosis` 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: api@system.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Suggested query.
 * @export
 * @interface SuggestedPubmedSearch
 */
export interface SuggestedPubmedSearch {
    /**
     * 
     * @type {string}
     * @memberof SuggestedPubmedSearch
     */
    query: string;
    /**
     * 
     * @type {number}
     * @memberof SuggestedPubmedSearch
     */
    numStudies: number;
}

/**
 * Check if a given object implements the SuggestedPubmedSearch interface.
 */
export function instanceOfSuggestedPubmedSearch(value: object): value is SuggestedPubmedSearch {
    if (!('query' in value) || value['query'] === undefined) return false;
    if (!('numStudies' in value) || value['numStudies'] === undefined) return false;
    return true;
}

export function SuggestedPubmedSearchFromJSON(json: any): SuggestedPubmedSearch {
    return SuggestedPubmedSearchFromJSONTyped(json, false);
}

export function SuggestedPubmedSearchFromJSONTyped(json: any, ignoreDiscriminator: boolean): SuggestedPubmedSearch {
    if (json == null) {
        return json;
    }
    return {
        
        'query': json['query'],
        'numStudies': json['num_studies'],
    };
}

export function SuggestedPubmedSearchToJSON(value?: SuggestedPubmedSearch | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'query': value['query'],
        'num_studies': value['numStudies'],
    };
}

