/* tslint:disable */
/* eslint-disable */
/**
 * System REST API
 *  This page provides documentation for the System REST API.  If you have any questions or need support, please contact us at the email provided.  ## Formatting query parameters  Filters should be formatted as `field:value` and use the logical OR operator `||` to specify an OR condition. (We\'ve deprecated the pipe operator for OR conditions.)   If they are numerical, they should be formatted as `field:opvalue`. Examples: - `doi:10.1234/5678||10.8765/4321` - `num_findings:>2`  Sorts should be formatted as `field:direction`. Examples: - `cited_by:desc` - `publish_date:asc`  Searches should be formatted as `field:value`. Examples: - `name:osteoporosis` 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: api@system.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Synthesis response.
 * @export
 * @interface Synthesis
 */
export interface Synthesis {
    /**
     * Thematic summaries of the findings.
     * @type {Array<{ [key: string]: string; }>}
     * @memberof Synthesis
     */
    summaries: Array<{ [key: string]: string; }>;
}

/**
 * Check if a given object implements the Synthesis interface.
 */
export function instanceOfSynthesis(value: object): value is Synthesis {
    if (!('summaries' in value) || value['summaries'] === undefined) return false;
    return true;
}

export function SynthesisFromJSON(json: any): Synthesis {
    return SynthesisFromJSONTyped(json, false);
}

export function SynthesisFromJSONTyped(json: any, ignoreDiscriminator: boolean): Synthesis {
    if (json == null) {
        return json;
    }
    return {
        
        'summaries': json['summaries'],
    };
}

export function SynthesisToJSON(value?: Synthesis | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'summaries': value['summaries'],
    };
}

