/* tslint:disable */
/* eslint-disable */
/**
 * System REST API
 *  This page provides documentation for the System REST API.  If you have any questions or need support, please contact us at the email provided.  ## Formatting query parameters  Filters should be formatted as `field:value` and use the logical OR operator `||` to specify an OR condition. (We\'ve deprecated the pipe operator for OR conditions.)   If they are numerical, they should be formatted as `field:opvalue`. Examples: - `doi:10.1234/5678||10.8765/4321` - `num_findings:>2`  Sorts should be formatted as `field:direction`. Examples: - `cited_by:desc` - `publish_date:asc`  Searches should be formatted as `field:value`. Examples: - `name:osteoporosis` 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: api@system.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Synthesis summary.
 * @export
 * @interface SynthesisSummary
 */
export interface SynthesisSummary {
    /**
     * Theme of the summary
     * @type {string}
     * @memberof SynthesisSummary
     */
    theme: string;
    /**
     * Summary of the theme
     * @type {string}
     * @memberof SynthesisSummary
     */
    summary: string;
}

/**
 * Check if a given object implements the SynthesisSummary interface.
 */
export function instanceOfSynthesisSummary(value: object): value is SynthesisSummary {
    if (!('theme' in value) || value['theme'] === undefined) return false;
    if (!('summary' in value) || value['summary'] === undefined) return false;
    return true;
}

export function SynthesisSummaryFromJSON(json: any): SynthesisSummary {
    return SynthesisSummaryFromJSONTyped(json, false);
}

export function SynthesisSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): SynthesisSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'theme': json['theme'],
        'summary': json['summary'],
    };
}

export function SynthesisSummaryToJSON(value?: SynthesisSummary | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'theme': value['theme'],
        'summary': value['summary'],
    };
}

