/* tslint:disable */
/* eslint-disable */
/**
 * System REST API
 *  This page provides documentation for the System REST API.  If you have any questions or need support, please contact us at the email provided.  ## Formatting query parameters  Filters should be formatted as `field:value` and use the logical OR operator `||` to specify an OR condition. (We\'ve deprecated the pipe operator for OR conditions.)   If they are numerical, they should be formatted as `field:opvalue`. Examples: - `doi:10.1234/5678||10.8765/4321` - `num_findings:>2`  Sorts should be formatted as `field:direction`. Examples: - `cited_by:desc` - `publish_date:asc`  Searches should be formatted as `field:value`. Examples: - `name:osteoporosis` 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: api@system.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Topic role.
 * @export
 */
export const TopicRole = {
    Determinant: 'Determinant',
    Intervention: 'Intervention',
    Outcome: 'Outcome',
    Agent: 'Agent'
} as const;
export type TopicRole = typeof TopicRole[keyof typeof TopicRole];


export function instanceOfTopicRole(value: any): boolean {
    for (const key in TopicRole) {
        if (Object.prototype.hasOwnProperty.call(TopicRole, key)) {
            if ((TopicRole as Record<string, TopicRole>)[key] === value) {
                return true;
            }
        }
    }
    return false;
}

export function TopicRoleFromJSON(json: any): TopicRole {
    return TopicRoleFromJSONTyped(json, false);
}

export function TopicRoleFromJSONTyped(json: any, ignoreDiscriminator: boolean): TopicRole {
    return json as TopicRole;
}

export function TopicRoleToJSON(value?: TopicRole | null): any {
    return value as any;
}

